apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nvflare-server.name" . }}
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nvflare-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nvflare-server.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ .Values.persistence.etc.friendlyName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.etc.claimName }}
        - name: {{ .Values.persistence.workspace.friendlyName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.workspace.claimName }}
      containers:
        - name: {{ include "nvflare-server.name" . }}
          image: {{ include "nvflare-server.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.persistence.etc.friendlyName }}
              mountPath: {{ .Values.persistence.etc.mountPath }}
            - name: {{ .Values.persistence.workspace.friendlyName }}
              mountPath: {{ .Values.persistence.workspace.mountPath }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.fedLearnPort }}
              hostPort: {{ .Values.fedLearnPort }}
              protocol: TCP
            {{- if .Values.adminPort }}
            - containerPort: {{ .Values.adminPort }}
              hostPort: {{ .Values.adminPort }}
              protocol: TCP
            {{- end }}
            - containerPort: {{ .Values.parentPort }}
              protocol: TCP
