apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvflare-server.name" . }}-ingress-controller
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "nvflare-server.name" . }}-ingress-controller
  ports:
    - name: fl-port
      protocol: TCP
      port: {{ .Values.fedLearnPort }}
      targetPort: {{ .Values.fedLearnPort }}
