{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nvflare-server.name" . }}-launcher
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nvflare-server.name" . }}-launcher
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nvflare-server.name" . }}-launcher
subjects:
- kind: ServiceAccount
  name: {{ include "nvflare-server.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
