apiVersion: v1
kind: Service
metadata:
  name: nvflare-server
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    {{- include "nvflare-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: fl-port
      protocol: TCP
      port: {{ .Values.fedLearnPort }}
      targetPort: {{ .Values.fedLearnPort }}
    {{- if .Values.adminPort }}
    - name: admin-port
      protocol: TCP
      port: {{ .Values.adminPort }}
      targetPort: {{ .Values.adminPort }}
    {{- end }}
    - name: nvflare-server
      protocol: TCP
      port: {{ .Values.parentPort }}
      targetPort: {{ .Values.parentPort }}
