apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nvflare-server.name" . }}
  labels:
    {{- include "nvflare-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "nvflare-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nvflare-server.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "nvflare-server.name" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.persistence.workspace.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.workspace.claimName }}
        {{- with .Values.workspaceConfig }}
        {{- with .local }}
        {{- if .configMapName }}
        - name: workspace-local
          configMap:
            name: {{ .configMapName }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- with .startup }}
        {{- if .secretName }}
        - name: workspace-startup
          secret:
            secretName: {{ .secretName }}
            {{- with .items }}
            items:
              {{- toYaml . | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ include "nvflare-server.name" . }}
          image: {{ include "nvflare-server.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: {{ .Values.persistence.workspace.volumeName }}
              mountPath: {{ .Values.persistence.workspace.mountPath }}
            {{- with .Values.workspaceConfig }}
            {{- with .local }}
            {{- if .configMapName }}
            - name: workspace-local
              mountPath: {{ $.Values.persistence.workspace.mountPath }}/local
              readOnly: true
            {{- end }}
            {{- end }}
            {{- with .startup }}
            {{- if .secretName }}
            - name: workspace-startup
              mountPath: {{ $.Values.persistence.workspace.mountPath }}/startup
              readOnly: true
            {{- end }}
            {{- end }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.fedLearnPort }}
              {{- if ne (include "nvflare-server.hostPortEnabled" .) "false" }}
              hostPort: {{ .Values.fedLearnPort }}
              {{- end }}
              protocol: TCP
            {{- if .Values.adminPort }}
            - containerPort: {{ .Values.adminPort }}
              {{- if ne (include "nvflare-server.hostPortEnabled" .) "false" }}
              hostPort: {{ .Values.adminPort }}
              {{- end }}
              protocol: TCP
            {{- end }}
            - containerPort: {{ .Values.parentPort }}
              protocol: TCP
