{{- if ne (include "nvflare-server.tcpConfigMapEnabled" .) "false" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-microk8s-conf
  namespace: ingress
data:
  {{ .Values.fedLearnPort | quote }}: {{ printf "%s/%s:%v" .Release.Namespace (include "nvflare-server.serviceName" .) .Values.fedLearnPort | quote }}
  {{- if .Values.adminPort }}
  {{ .Values.adminPort | quote }}: {{ printf "%s/%s:%v" .Release.Namespace (include "nvflare-server.serviceName" .) .Values.adminPort | quote }}
  {{- end }}
{{- end }}
