# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import tempfile
from unittest.mock import patch

import pytest

from nvflare.recipe.poc_env import PocEnv
from nvflare.tool.poc.service_constants import FlareServiceConstants as SC


def test_poc_env_initialization():
    """Test PocEnv initialization with default values."""
    env = PocEnv()
    assert env.num_clients == 2
    assert env.gpu_ids == []


@patch("nvflare.recipe.poc_env.get_poc_workspace")
def test_poc_env_initialization_with_custom_values(mock_get_workspace):
    """Test PocEnv initialization with custom values."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        env = PocEnv(
            num_clients=3,
            gpu_ids=[0, 1],
        )
        assert env.poc_workspace == temp_dir
        assert env.num_clients == 3
        assert env.gpu_ids == [0, 1]


def test_poc_env_validation():
    """Test PocEnv validation for invalid configurations."""
    # Test with zero clients (invalid)
    with pytest.raises(ValueError, match="Input should be greater than 0"):
        PocEnv(num_clients=0)

    # Test with negative clients (invalid)
    with pytest.raises(ValueError, match="Input should be greater than 0"):
        PocEnv(num_clients=-1)

    # Test with empty clients list (invalid)
    with pytest.raises(ValueError, match="clients list cannot be empty"):
        PocEnv(clients=[])

    # Test with inconsistent num_clients and clients
    with pytest.raises(ValueError, match="Inconsistent"):
        PocEnv(num_clients=3, clients=["site1", "site2"])


def test_poc_env_none_num_clients_raises():
    """Test that PocEnv(num_clients=None) raises ValueError instead of crashing with TypeError."""
    with pytest.raises(ValueError, match="num_clients must be greater than 0"):
        PocEnv(num_clients=None, clients=None)


def test_poc_env_client_names():
    """Test PocEnv client name generation and validation."""
    # Test auto-generated client names (delegated to prepare_poc_provision)
    env = PocEnv(num_clients=3)
    assert env.clients is None  # Will be generated by prepare_poc_provision
    assert env.num_clients == 3

    # Test custom client names
    custom_clients = ["client-a", "client-b"]
    env = PocEnv(clients=custom_clients)
    assert env.clients == custom_clients
    assert env.num_clients == 2

    # Test consistent num_clients and clients
    env = PocEnv(num_clients=2, clients=["site-x", "site-y"])
    assert env.clients == ["site-x", "site-y"]
    assert env.num_clients == 2


@patch("nvflare.recipe.poc_env.get_poc_workspace")
@patch("nvflare.recipe.poc_env.get_prod_dir")
@patch("nvflare.recipe.poc_env.setup_service_config")
def test_get_admin_startup_kit_path(mock_setup, mock_get_prod_dir, mock_get_workspace):
    """Test getting admin startup kit path."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        prod_dir = os.path.join(temp_dir, "prod_00")
        mock_get_prod_dir.return_value = prod_dir
        mock_setup.return_value = ({"name": "test_project"}, {SC.FLARE_PROJ_ADMIN: "admin@nvidia.com"})

        env = PocEnv()

        # Create the expected admin directory structure
        admin_dir = os.path.join(prod_dir, "admin@nvidia.com")
        os.makedirs(admin_dir, exist_ok=True)

        result = env._get_admin_startup_kit_path()
        assert result == admin_dir


@patch("nvflare.recipe.poc_env.get_poc_workspace")
@patch("nvflare.recipe.poc_env.get_prod_dir")
@patch("nvflare.recipe.poc_env.setup_service_config")
def test_get_admin_startup_kit_path_not_found(mock_setup, mock_get_prod_dir, mock_get_workspace):
    """Test getting admin startup kit path when directory doesn't exist."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        prod_dir = os.path.join(temp_dir, "prod_00")
        mock_get_prod_dir.return_value = prod_dir
        mock_setup.return_value = ({"name": "test_project"}, {SC.FLARE_PROJ_ADMIN: "admin@nvidia.com"})

        env = PocEnv()

        with pytest.raises(RuntimeError, match="Admin startup kit not found"):
            env._get_admin_startup_kit_path()


@patch("nvflare.recipe.poc_env.setup_service_config")
@patch("nvflare.recipe.poc_env._stop_poc")
@patch("nvflare.recipe.poc_env._clean_poc")
@patch("nvflare.recipe.poc_env.is_poc_running")
def test_stop_poc(mock_is_running, mock_clean_poc, mock_stop_poc, mock_setup):
    """Test stop and clean POC functionality."""
    mock_setup.return_value = ({"name": "test"}, {"server": "server"})
    # Mock is_poc_running to return True initially (POC is running),
    # then False (POC stops successfully after _stop_poc is called)
    mock_is_running.side_effect = [True, False]

    env = PocEnv()
    env.stop(clean_up=True)

    mock_stop_poc.assert_called_once_with(
        poc_workspace=env.poc_workspace, excluded=["admin@nvidia.com"], services_list=[]
    )
    # _clean_poc handles workspace removal internally via shutil.rmtree
    mock_clean_poc.assert_called_once_with(env.poc_workspace)
