# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import tempfile
from unittest.mock import patch

import pytest

from nvflare.recipe.poc_env import PocEnv
from nvflare.tool.poc.service_constants import FlareServiceConstants as SC


def test_poc_env_initialization():
    """Test PocEnv initialization with default values."""
    env = PocEnv()
    assert env.num_clients == 2
    assert env.gpu_ids == []
    assert env.study == "default"
    assert env.deployment_started is False
    assert env.workspace_owned is False


@patch("nvflare.recipe.poc_env.get_poc_workspace")
def test_poc_env_initialization_with_custom_values(mock_get_workspace):
    """Test PocEnv initialization with custom values."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        env = PocEnv(
            num_clients=3,
            gpu_ids=[0, 1],
        )
        assert env.poc_workspace == temp_dir
        assert env.num_clients == 3
        assert env.gpu_ids == [0, 1]


def test_poc_env_validation():
    """Test PocEnv validation for invalid configurations."""
    # Test with zero clients (invalid)
    with pytest.raises(ValueError, match="Input should be greater than 0"):
        PocEnv(num_clients=0)

    # Test with negative clients (invalid)
    with pytest.raises(ValueError, match="Input should be greater than 0"):
        PocEnv(num_clients=-1)

    # Test with empty clients list (invalid)
    with pytest.raises(ValueError, match="clients list cannot be empty"):
        PocEnv(clients=[])

    # Test with inconsistent num_clients and clients
    with pytest.raises(ValueError, match="Inconsistent"):
        PocEnv(num_clients=3, clients=["site1", "site2"])


def test_poc_env_none_num_clients_raises():
    """Test that PocEnv(num_clients=None) raises ValueError instead of crashing with TypeError."""
    with pytest.raises(ValueError, match="num_clients must be greater than 0"):
        PocEnv(num_clients=None, clients=None)


def test_poc_env_client_names():
    """Test PocEnv client name generation and validation."""
    # Test auto-generated client names (delegated to prepare_poc_provision)
    env = PocEnv(num_clients=3)
    assert env.clients is None  # Will be generated by prepare_poc_provision
    assert env.num_clients == 3

    # Test custom client names
    custom_clients = ["client-a", "client-b"]
    env = PocEnv(clients=custom_clients)
    assert env.clients == custom_clients
    assert env.num_clients == 2

    # Test consistent num_clients and clients
    env = PocEnv(num_clients=2, clients=["site-x", "site-y"])
    assert env.clients == ["site-x", "site-y"]
    assert env.num_clients == 2


@patch("nvflare.recipe.poc_env.get_poc_workspace")
def test_poc_env_initialization_with_study(mock_get_workspace):
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        env = PocEnv(num_clients=2, study="cancer-research")

        assert env.study == "cancer-research"


def test_poc_env_rejects_invalid_study_name():
    with pytest.raises(ValueError):
        PocEnv(study="Bad Study")


@patch("nvflare.recipe.poc_env.collect_non_local_scripts", return_value=["missing.py"])
def test_deploy_preflight_failure_does_not_start_lifecycle(mock_collect_non_local_scripts):
    env = PocEnv()

    with pytest.raises(ValueError, match="scripts do not exist locally"):
        env.deploy(object())

    assert env.deployment_started is False
    assert env.workspace_owned is False


@patch("nvflare.recipe.poc_env.get_poc_workspace")
@patch("nvflare.recipe.poc_env.prepare_poc_provision", side_effect=RuntimeError("provisioning failed"))
@patch.object(PocEnv, "_check_poc_running", return_value=False)
@patch("nvflare.recipe.poc_env.collect_non_local_scripts", return_value=[])
def test_deploy_marks_lifecycle_started_before_provisioning(
    mock_collect_non_local_scripts, mock_check_poc_running, mock_prepare_poc_provision, mock_get_workspace, tmp_path
):
    mock_get_workspace.return_value = str(tmp_path / "new-poc-workspace")
    env = PocEnv()

    with pytest.raises(RuntimeError, match="provisioning failed"):
        env.deploy(object())

    assert env.deployment_started is True
    assert env.workspace_owned is True


@patch("nvflare.recipe.poc_env.prepare_poc_provision", side_effect=RuntimeError("provisioning failed"))
@patch.object(PocEnv, "_check_poc_running", return_value=False)
@patch("nvflare.recipe.poc_env.collect_non_local_scripts", return_value=[])
@patch("nvflare.recipe.poc_env.get_poc_workspace")
def test_failed_provisioning_does_not_claim_existing_workspace(
    mock_get_workspace, mock_collect_non_local_scripts, mock_check_poc_running, mock_prepare_poc_provision, tmp_path
):
    workspace = tmp_path / "retained-poc-workspace"
    workspace.mkdir()
    retained_result = workspace / "prior-result.txt"
    retained_result.write_text("keep me")
    mock_get_workspace.return_value = str(workspace)
    env = PocEnv()

    with pytest.raises(RuntimeError, match="provisioning failed"):
        env.deploy(object())

    assert env.deployment_started is True
    assert env.workspace_owned is False
    assert retained_result.read_text() == "keep me"
    assert not list(tmp_path.glob("retained-poc-workspace.nvflare-recipe-backup-*"))


def test_failed_provisioning_restores_workspace_after_partial_writes(tmp_path, monkeypatch):
    import nvflare.recipe.poc_env as poc_env_module

    workspace = tmp_path / "replaced-poc-workspace"
    workspace.mkdir()
    (workspace / "prior-result.txt").write_text("old")
    monkeypatch.setattr(poc_env_module, "get_poc_workspace", lambda: str(workspace))
    monkeypatch.setattr(poc_env_module, "collect_non_local_scripts", lambda job: [])
    monkeypatch.setattr(PocEnv, "_check_poc_running", lambda self: False)

    def write_then_fail(**kwargs):
        workspace.mkdir()
        (workspace / "partial-result.txt").write_text("partial")
        raise RuntimeError("provisioning failed after partial writes")

    monkeypatch.setattr(poc_env_module, "prepare_poc_provision", write_then_fail)
    env = PocEnv()

    with pytest.raises(RuntimeError, match="failed after partial writes"):
        env.deploy(object())

    assert env.deployment_started is True
    assert env.workspace_owned is False
    assert (workspace / "prior-result.txt").read_text() == "old"
    assert not (workspace / "partial-result.txt").exists()
    assert not list(tmp_path.glob("replaced-poc-workspace.nvflare-recipe-backup-*"))


def test_failed_start_restores_retained_workspace(tmp_path, monkeypatch):
    import nvflare.recipe.poc_env as poc_env_module

    workspace = tmp_path / "start-failure-workspace"
    workspace.mkdir()
    (workspace / "prior-result.txt").write_text("old")
    monkeypatch.setattr(poc_env_module, "get_poc_workspace", lambda: str(workspace))
    monkeypatch.setattr(poc_env_module, "collect_non_local_scripts", lambda job: [])
    monkeypatch.setattr(PocEnv, "_check_poc_running", lambda self: False)
    monkeypatch.setattr(poc_env_module, "prepare_poc_provision", lambda **kwargs: workspace.mkdir())

    def fail_start(**kwargs):
        raise RuntimeError("start failed")

    monkeypatch.setattr(poc_env_module, "_start_poc", fail_start)
    env = PocEnv()

    with pytest.raises(RuntimeError, match="start failed"):
        env.deploy(object())

    assert env.deployment_started is True
    assert env.workspace_owned is False
    assert (workspace / "prior-result.txt").read_text() == "old"
    assert not list(tmp_path.glob("start-failure-workspace.nvflare-recipe-backup-*"))


@patch("nvflare.recipe.poc_env.get_poc_workspace")
@patch("nvflare.recipe.poc_env.get_prod_dir")
@patch("nvflare.recipe.poc_env.setup_service_config")
def test_get_admin_startup_kit_path(mock_setup, mock_get_prod_dir, mock_get_workspace):
    """Test getting admin startup kit path."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        prod_dir = os.path.join(temp_dir, "prod_00")
        mock_get_prod_dir.return_value = prod_dir
        mock_setup.return_value = ({"name": "test_project"}, {SC.FLARE_PROJ_ADMIN: "admin@nvidia.com"})

        env = PocEnv()

        # Create the expected admin directory structure
        admin_dir = os.path.join(prod_dir, "admin@nvidia.com")
        os.makedirs(admin_dir, exist_ok=True)

        result = env._get_admin_startup_kit_path()
        assert result == admin_dir


@patch("nvflare.recipe.poc_env.get_poc_workspace")
@patch("nvflare.recipe.poc_env.get_prod_dir")
@patch("nvflare.recipe.poc_env.setup_service_config")
def test_get_admin_startup_kit_path_not_found(mock_setup, mock_get_prod_dir, mock_get_workspace):
    """Test getting admin startup kit path when directory doesn't exist."""
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        prod_dir = os.path.join(temp_dir, "prod_00")
        mock_get_prod_dir.return_value = prod_dir
        mock_setup.return_value = ({"name": "test_project"}, {SC.FLARE_PROJ_ADMIN: "admin@nvidia.com"})

        env = PocEnv()

        with pytest.raises(RuntimeError, match="Admin startup kit not found"):
            env._get_admin_startup_kit_path()


@patch("nvflare.recipe.poc_env.setup_service_config")
@patch("nvflare.recipe.poc_env._stop_poc")
@patch("nvflare.recipe.poc_env._clean_poc")
@patch("nvflare.recipe.poc_env.is_poc_running")
def test_stop_poc(mock_is_running, mock_clean_poc, mock_stop_poc, mock_setup):
    """Test stop and clean POC functionality."""
    mock_setup.return_value = ({"name": "test"}, {"server": "server"})
    # Mock is_poc_running to return True initially (POC is running),
    # then False (POC stops successfully after _stop_poc is called)
    mock_is_running.side_effect = [True, False]

    env = PocEnv()
    env.stop(clean_up=True)

    mock_stop_poc.assert_called_once_with(
        poc_workspace=env.poc_workspace, excluded=["admin@nvidia.com"], services_list=[]
    )
    # _clean_poc handles workspace removal internally via shutil.rmtree
    mock_clean_poc.assert_called_once_with(env.poc_workspace)


@patch("nvflare.recipe.poc_env.SessionManager")
@patch("nvflare.recipe.poc_env.setup_service_config")
@patch("nvflare.recipe.poc_env.get_prod_dir")
@patch("nvflare.recipe.poc_env.get_poc_workspace")
def test_poc_env_session_manager_passes_study(mock_get_workspace, mock_get_prod_dir, mock_setup, mock_session_manager):
    with tempfile.TemporaryDirectory() as temp_dir:
        mock_get_workspace.return_value = temp_dir
        prod_dir = os.path.join(temp_dir, "prod_00")
        mock_get_prod_dir.return_value = prod_dir
        mock_setup.return_value = ({"name": "test_project"}, {SC.FLARE_PROJ_ADMIN: "admin@nvidia.com"})

        admin_dir = os.path.join(prod_dir, "admin@nvidia.com")
        os.makedirs(admin_dir, exist_ok=True)

        env = PocEnv(study="cancer-research")
        env._get_session_manager()

        session_params = mock_session_manager.call_args[0][0]
        assert session_params["study"] == "cancer-research"
