# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: federated.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\x11xgboost.federated\"N\n\x10\x41llgatherRequest\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x13\n\x0bsend_buffer\x18\x03 \x01(\x0c\"(\n\x0e\x41llgatherReply\x12\x16\n\x0ereceive_buffer\x18\x01 \x01(\x0c\"\xbc\x01\n\x10\x41llreduceRequest\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x13\n\x0bsend_buffer\x18\x03 \x01(\x0c\x12.\n\tdata_type\x18\x04 \x01(\x0e\x32\x1b.xgboost.federated.DataType\x12<\n\x10reduce_operation\x18\x05 \x01(\x0e\x32\".xgboost.federated.ReduceOperation\"(\n\x0e\x41llreduceReply\x12\x16\n\x0ereceive_buffer\x18\x01 \x01(\x0c\"\\\n\x10\x42roadcastRequest\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x0c\n\x04rank\x18\x02 \x01(\x05\x12\x13\n\x0bsend_buffer\x18\x03 \x01(\x0c\x12\x0c\n\x04root\x18\x04 \x01(\x05\"(\n\x0e\x42roadcastReply\x12\x16\n\x0ereceive_buffer\x18\x01 \x01(\x0c*{\n\x08\x44\x61taType\x12\x08\n\x04\x43HAR\x10\x00\x12\t\n\x05UCHAR\x10\x01\x12\x07\n\x03INT\x10\x02\x12\x08\n\x04UINT\x10\x03\x12\x08\n\x04LONG\x10\x04\x12\t\n\x05ULONG\x10\x05\x12\t\n\x05\x46LOAT\x10\x06\x12\n\n\x06\x44OUBLE\x10\x07\x12\x0c\n\x08LONGLONG\x10\x08\x12\r\n\tULONGLONG\x10\t*,\n\x0fReduceOperation\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03MIN\x10\x01\x12\x07\n\x03SUM\x10\x02\x32\x90\x02\n\tFederated\x12U\n\tAllgather\x12#.xgboost.federated.AllgatherRequest\x1a!.xgboost.federated.AllgatherReply\"\x00\x12U\n\tAllreduce\x12#.xgboost.federated.AllreduceRequest\x1a!.xgboost.federated.AllreduceReply\"\x00\x12U\n\tBroadcast\x12#.xgboost.federated.BroadcastRequest\x1a!.xgboost.federated.BroadcastReply\"\x00\x62\x06proto3')

_DATATYPE = DESCRIPTOR.enum_types_by_name['DataType']
DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
_REDUCEOPERATION = DESCRIPTOR.enum_types_by_name['ReduceOperation']
ReduceOperation = enum_type_wrapper.EnumTypeWrapper(_REDUCEOPERATION)
CHAR = 0
UCHAR = 1
INT = 2
UINT = 3
LONG = 4
ULONG = 5
FLOAT = 6
DOUBLE = 7
LONGLONG = 8
ULONGLONG = 9
MAX = 0
MIN = 1
SUM = 2


_ALLGATHERREQUEST = DESCRIPTOR.message_types_by_name['AllgatherRequest']
_ALLGATHERREPLY = DESCRIPTOR.message_types_by_name['AllgatherReply']
_ALLREDUCEREQUEST = DESCRIPTOR.message_types_by_name['AllreduceRequest']
_ALLREDUCEREPLY = DESCRIPTOR.message_types_by_name['AllreduceReply']
_BROADCASTREQUEST = DESCRIPTOR.message_types_by_name['BroadcastRequest']
_BROADCASTREPLY = DESCRIPTOR.message_types_by_name['BroadcastReply']
AllgatherRequest = _reflection.GeneratedProtocolMessageType('AllgatherRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLGATHERREQUEST,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.AllgatherRequest)
  })
_sym_db.RegisterMessage(AllgatherRequest)

AllgatherReply = _reflection.GeneratedProtocolMessageType('AllgatherReply', (_message.Message,), {
  'DESCRIPTOR' : _ALLGATHERREPLY,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.AllgatherReply)
  })
_sym_db.RegisterMessage(AllgatherReply)

AllreduceRequest = _reflection.GeneratedProtocolMessageType('AllreduceRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALLREDUCEREQUEST,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.AllreduceRequest)
  })
_sym_db.RegisterMessage(AllreduceRequest)

AllreduceReply = _reflection.GeneratedProtocolMessageType('AllreduceReply', (_message.Message,), {
  'DESCRIPTOR' : _ALLREDUCEREPLY,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.AllreduceReply)
  })
_sym_db.RegisterMessage(AllreduceReply)

BroadcastRequest = _reflection.GeneratedProtocolMessageType('BroadcastRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTREQUEST,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.BroadcastRequest)
  })
_sym_db.RegisterMessage(BroadcastRequest)

BroadcastReply = _reflection.GeneratedProtocolMessageType('BroadcastReply', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTREPLY,
  '__module__' : 'mpi_pb2'
  # @@protoc_insertion_point(class_scope:xgboost.federated.BroadcastReply)
  })
_sym_db.RegisterMessage(BroadcastReply)

_FEDERATED = DESCRIPTOR.services_by_name['Federated']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATATYPE._serialized_start=529
  _DATATYPE._serialized_end=652
  _REDUCEOPERATION._serialized_start=654
  _REDUCEOPERATION._serialized_end=698
  _ALLGATHERREQUEST._serialized_start=38
  _ALLGATHERREQUEST._serialized_end=116
  _ALLGATHERREPLY._serialized_start=118
  _ALLGATHERREPLY._serialized_end=158
  _ALLREDUCEREQUEST._serialized_start=161
  _ALLREDUCEREQUEST._serialized_end=349
  _ALLREDUCEREPLY._serialized_start=351
  _ALLREDUCEREPLY._serialized_end=391
  _BROADCASTREQUEST._serialized_start=393
  _BROADCASTREQUEST._serialized_end=485
  _BROADCASTREPLY._serialized_start=487
  _BROADCASTREPLY._serialized_end=527
  _FEDERATED._serialized_start=701
  _FEDERATED._serialized_end=973
# @@protoc_insertion_point(module_scope)
