# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edge_api.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'edge_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65\x64ge_api.proto\x12\x07\x65\x64geapi\"X\n\x07Request\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x0e\n\x06header\x18\x03 \x01(\x0c\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x0e\n\x06\x63ookie\x18\x05 \x01(\x0c\"8\n\x05Reply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x0e\n\x06\x63ookie\x18\x03 \x01(\x0c\x32\x36\n\x07\x45\x64geApi\x12+\n\x05Query\x12\x10.edgeapi.Request\x1a\x0e.edgeapi.Reply\"\x00\x42\x07\xa2\x02\x04\x45\x44GEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edge_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\004EDGE'
  _globals['_REQUEST']._serialized_start=27
  _globals['_REQUEST']._serialized_end=115
  _globals['_REPLY']._serialized_start=117
  _globals['_REPLY']._serialized_end=173
  _globals['_EDGEAPI']._serialized_start=175
  _globals['_EDGEAPI']._serialized_end=229
# @@protoc_insertion_point(module_scope)
