#!/usr/bin/env bash
# Generated by NVFlare deploy prepare - Docker runtime @@NVFLARE_ROLE_LABEL@@ startup script.
# The parent @@NVFLARE_ROLE_LABEL@@ container mounts this prepared kit and launches job containers through Docker.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
HOST_WORKSPACE="$(cd "$DIR/.." && pwd)"
DOCKER_IMAGE=${NVFL_P_IMAGE:-@@NVFLARE_DOCKER_IMAGE@@}
DOCKER_SOCK="${NVFL_DOCKER_SOCK:-/var/run/docker.sock}"

if [ -z "${NVFL_DOCKER_SOCK:-}" ] && [ -L "$DOCKER_SOCK" ]; then
    RESOLVED_DOCKER_SOCK=$(readlink "$DOCKER_SOCK")
    if [ -n "$RESOLVED_DOCKER_SOCK" ]; then
        case "$RESOLVED_DOCKER_SOCK" in
            /*)
                DOCKER_SOCK="$RESOLVED_DOCKER_SOCK"
                ;;
            *)
                RESOLVED_DOCKER_SOCK_DIR="$(
                    cd "$(dirname "$DOCKER_SOCK")" &&
                    cd "$(dirname "$RESOLVED_DOCKER_SOCK")" &&
                    pwd
                )"
                DOCKER_SOCK="$RESOLVED_DOCKER_SOCK_DIR/$(basename "$RESOLVED_DOCKER_SOCK")"
                ;;
        esac
    fi
fi

if [ ! -S "$DOCKER_SOCK" ]; then
    echo "ERROR: Docker socket not found or not a socket: $DOCKER_SOCK"
    echo "Set NVFL_DOCKER_SOCK=/path/to/docker.sock to override the Docker socket path."
    exit 1
fi

DOCKER_HOST_URI="unix://$DOCKER_SOCK"

if ! docker --host "$DOCKER_HOST_URI" info > /dev/null 2>&1; then
    echo "ERROR: cannot connect to Docker daemon. Make sure your user has permission to run docker."
    echo "  Option 1 (docker group): sudo usermod -aG docker \$USER  then log out and back in."
    echo "  Option 2 (rootless Docker): https://docs.docker.com/engine/security/rootless/"
    exit 1
fi

echo "Starting NVFlare @@NVFLARE_ROLE_LABEL@@ @@NVFLARE_SITE_NAME@@ with image $DOCKER_IMAGE"
echo "Host workspace: $HOST_WORKSPACE"

NETWORK_NAME=@@NVFLARE_NETWORK_NAME@@
if ! docker --host "$DOCKER_HOST_URI" network ls --filter name="$NETWORK_NAME" --format "{{.Name}}" | grep -wq "$NETWORK_NAME"; then
    docker --host "$DOCKER_HOST_URI" network create "$NETWORK_NAME"
    echo "Created Docker network: $NETWORK_NAME"
fi

rm -f "$HOST_WORKSPACE/daemon_pid.fl"

SOCK_GID=$(stat -c '%g' "$DOCKER_SOCK" 2>/dev/null || stat -f '%g' "$DOCKER_SOCK" 2>/dev/null || echo "")
GROUP_ADD_ARGS=(--group-add 0)
if [ -n "$SOCK_GID" ] && [ "$SOCK_GID" != "0" ]; then
    GROUP_ADD_ARGS+=(--group-add "$SOCK_GID")
fi

docker --host "$DOCKER_HOST_URI" run --name @@NVFLARE_CONTAINER_NAME@@ \
    --user "$(id -u):$(id -g)" \
    "${GROUP_ADD_ARGS[@]}" \
    --network "$NETWORK_NAME" \
@@NVFLARE_NETWORK_ALIAS@@    -v "$HOST_WORKSPACE":@@NVFLARE_WORKSPACE_MOUNT_PATH@@ \
    -v "$DOCKER_SOCK":/var/run/docker.sock \
    -e NVFL_DOCKER_WORKSPACE="$HOST_WORKSPACE" \
@@NVFLARE_PUBLISH_PORTS@@    --rm "$DOCKER_IMAGE" \
    @@NVFLARE_PARENT_COMMAND@@
