apiVersion: v1
kind: Service
metadata:
  name: {{ include "nvflare-client.name" . }}
  labels:
    {{- include "nvflare-client.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nvflare-client.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
