# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Dict, Tuple

CLI_ERRORS: Dict[str, Tuple[str, str]] = {
    # --- General ---
    "CONNECTION_FAILED": (
        "Cannot connect to server at {host}:{port}.",
        "Check that the server is running and the startup kit path is correct.",
    ),
    "AUTH_FAILED": (
        "Authentication failed for user {username}.",
        "Check that the startup kit credentials are valid.",
    ),
    "TIMEOUT": (
        "Operation timed out after {timeout}s.",
        "Increase --timeout or check server load.",
    ),
    "OUTPUT_DIR_NOT_WRITABLE": (
        "Cannot write to output directory {path}: {detail}",
        "Check directory permissions or choose a different output directory.",
    ),
    "CERT_GENERATION_FAILED": (
        "Failed to generate certificate: {detail}",
        "Check that the cryptography package is installed and up-to-date.",
    ),
    "INVALID_ARGS": (
        "Invalid arguments: {detail}",
        "Run with --help for usage.",
    ),
    # --- Cert commands ---
    "CA_ALREADY_EXISTS": (
        "Root CA already exists at {path}.",
        "Use --force to overwrite, or choose a different output directory.",
    ),
    "CA_NOT_FOUND": (
        "No root CA found at {ca_dir}.",
        "Run 'nvflare cert init' first, or specify the correct --ca-dir.",
    ),
    "CSR_NOT_FOUND": (
        "CSR file not found: {path}.",
        "Check the path to the .csr file.",
    ),
    "INVALID_CSR": (
        "Invalid or corrupt CSR file: {path}.",
        "Regenerate the CSR with 'nvflare cert csr'.",
    ),
    "CERT_ALREADY_EXISTS": (
        "Signed certificate already exists at {path}.",
        "Use --force to overwrite.",
    ),
    "INVALID_CERT_TYPE": (
        "Invalid certificate type '{cert_type}'.",
        "Use one of: client, server, org_admin, lead, member.",
    ),
    "KEY_ALREADY_EXISTS": (
        "Private key already exists at {path}.",
        "Use --force to overwrite, or choose a different output directory.",
    ),
    "INVALID_NAME": (
        "Invalid name '{name}': {reason}",
        "The name must be 64 characters or fewer and must not contain leading/trailing whitespace.",
    ),
    # --- Package command ---
    "CERT_NOT_FOUND": (
        "Certificate file not found: {path}.",
        "Provide the signed certificate received from the Project Admin.",
    ),
    "KEY_NOT_FOUND": (
        "Private key file not found: {path}.",
        "Provide the private key generated by 'nvflare cert csr'.",
    ),
    "ROOTCA_NOT_FOUND": (
        "Root CA file not found: {path}.",
        "Provide the rootCA.pem received from the Project Admin.",
    ),
    "INVALID_ENDPOINT": (
        "Invalid endpoint URI: {endpoint}.",
        "Use format: grpc://host:port, tcp://host:port, or http://host:port.",
    ),
    "OUTPUT_DIR_EXISTS": (
        "Output directory already exists: {path}.",
        "Use --force to package into a new prod_NN stage directory.",
    ),
    "AMBIGUOUS_KEY": (
        "Multiple *.key files found in {path}: {files}",
        "--dir mode packages one participant at a time. "
        "Use -n to select one, use --key/--cert explicitly, "
        "or use --project-file to package all participants in one command.",
    ),
    "UNSIGNED_JOB_REJECTED": (
        "Unsigned job rejected — require_signed_jobs is enabled.",
        "Sign the job with an admin cert, or disable require_signed_jobs in fed_server.json.",
    ),
    "CERT_CHAIN_INVALID": (
        "Certificate {cert} is not signed by root CA {rootca}.",
        "Ensure the cert was signed by the Project Admin using the same root CA.",
    ),
    "CERT_EXPIRED": (
        "Certificate {cert} expired at {expiry}.",
        "Request a new certificate from the Project Admin.",
    ),
    "CSR_GENERATION_FAILED": (
        "CSR generation failed: {detail}",
        "Check that the cryptography package is installed and up-to-date.",
    ),
    "CERT_TYPE_UNKNOWN": (
        "Unknown certificate type in '{cert}': the type embedded by 'nvflare cert sign' is missing or unrecognized.",
        "Re-sign the CSR with 'nvflare cert sign -t <type>' to embed the correct type (client, server, lead, org_admin, or member).",
    ),
    "CERT_SIGNING_FAILED": (
        "Certificate signing failed: {reason}",
        "Check that the CA key and certificate are valid and not corrupted.",
    ),
    # --- Package yaml mode ---
    "PROJECT_FILE_NOT_FOUND": (
        "Project file not found: {path}.",
        "Provide the path to a site-scoped project yaml file.",
    ),
    "INVALID_PROJECT_FILE": (
        "Invalid project file: {detail}",
        "Ensure the file is schema-compatible with 'nvflare provision' project.yaml (api_version: 3).",
    ),
    "UNSUPPORTED_TOPOLOGY": (
        "Relay participants found in project file — hierarchical FL is not supported by 'nvflare package'.",
        "Use 'nvflare provision' for relay topologies.",
    ),
    "NO_PARTICIPANTS": (
        "No participants to build after applying type filter.",
        "Check the project file and -t filter.",
    ),
    # --- Job commands ---
    "JOB_NOT_FOUND": (
        "Job '{job_id}' does not exist on this server.",
        "Use 'nvflare job list' to see available job IDs.",
    ),
}


def get_error(code: str, **kwargs) -> Tuple[str, str]:
    """Return (message, hint) for the given error code, with placeholders filled.

    If the code is not registered, returns a generic fallback tuple.
    """
    template, hint = CLI_ERRORS.get(code, ("Unknown error.", "Check logs for details."))
    try:
        message = template.format(**kwargs)
    except KeyError:
        message = template
    return message, hint
