# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Stream contract for all nvflare CLI command handlers
=====================================================

Default (human-first):
    stdout — human-readable output (tables, summaries, prompts).
    stderr — errors and diagnostics.

Agent mode (set NVFLARE_CLI_MODE=agent):
    stdout — exactly one JSON envelope per command invocation:
        {"schema_version": "1", "status": "ok"|"error", "data": {...}}
    stderr — all human-readable output: progress, warnings, prompts, diagnostics.

Exceptions (plain text, outside the JSON contract):
    --help / -h         argparse usage text; agents use --schema instead
    --version           top-level utility path, not command output
    argparse errors     unrecognised-argument messages generated by argparse
"""

import json
import os
import sys
from typing import Any, Optional

SCHEMA_VERSION = "1"
_CLI_MODE_ENV = "NVFLARE_CLI_MODE"


def _agent_mode() -> bool:
    value = os.getenv(_CLI_MODE_ENV, "")
    return value.strip().lower() in {"agent", "json", "machine", "1", "true", "yes"}


def _human_stream():
    return sys.stderr if _agent_mode() else sys.stdout


def _render_table(data: Any) -> None:
    if isinstance(data, dict):
        for k, v in data.items():
            print(f"{k}: {v}")
    elif isinstance(data, list):
        if not data:
            return
        if isinstance(data[0], dict):
            keys = list(data[0].keys())
            widths = [max(len(k), max(len(str(r.get(k, ""))) for r in data)) for k in keys]
            header = "  ".join(k.ljust(w) for k, w in zip(keys, widths))
            print(header)
            print("-" * len(header))
            for row in data:
                print("  ".join(str(row.get(k, "")).ljust(w) for k, w in zip(keys, widths)))
        else:
            for item in data:
                print(item)
    else:
        print(str(data))


def output(data: Any, fmt: Optional[str]) -> None:
    """Print command result in requested format. Used by cert/package commands."""
    if fmt is None and _agent_mode():
        fmt = "json"
    if fmt == "json":
        print(json.dumps({"schema_version": SCHEMA_VERSION, "status": "ok", "data": data}))
    elif fmt == "quiet":
        if isinstance(data, dict):
            print(next(iter(data.values()), ""))
        elif isinstance(data, list):
            print(data[0] if data else "")
        else:
            print(str(data))
    else:
        _render_table(data)


def output_ok(data: Any) -> None:
    """Print command success output."""
    if _agent_mode():
        print(json.dumps({"schema_version": SCHEMA_VERSION, "status": "ok", "data": data}))
    else:
        _render_table(data)


def output_error(
    error_code: str,
    message: str = None,
    hint: str = None,
    fmt: Optional[str] = None,
    exit_code: int = 1,
    detail: str = None,
    **kwargs,
) -> None:
    """Print error envelope and exit. Never returns.

    Two calling patterns:
    - Cert/package: output_error(code, message, hint, fmt, exit_code=N)
    - Phase 0+1:    output_error(code, exit_code=N, job_id="abc", detail="...")
    """
    if message is None:
        # Phase 0+1: look up from ERROR_REGISTRY, emit JSON in agent mode
        from nvflare.tool.cli_errors import ERROR_REGISTRY

        entry = ERROR_REGISTRY.get(error_code, {"message": error_code, "hint": ""})
        try:
            message = entry["message"].format_map(kwargs) if kwargs else entry["message"]
        except KeyError:
            message = entry["message"]
        if detail:
            message = f"{message} \u2014 {detail}"
        if _agent_mode():
            print(
                json.dumps(
                    {
                        "schema_version": SCHEMA_VERSION,
                        "status": "error",
                        "error_code": error_code,
                        "message": message,
                        "hint": entry["hint"],
                    }
                )
            )
        else:
            print(f"ERROR_CODE: {error_code}", file=sys.stderr)
            print(message, file=sys.stderr)
            if entry["hint"]:
                print(f"Hint: {entry['hint']}", file=sys.stderr)
    else:
        # Cert/package: explicit message/hint provided; fmt determines output format
        resolved_hint = hint or ""
        if detail:
            message = f"{message} \u2014 {detail}"
        if fmt == "json" or (fmt is None and _agent_mode()):
            print(
                json.dumps(
                    {
                        "schema_version": SCHEMA_VERSION,
                        "status": "error",
                        "error_code": error_code,
                        "message": message,
                        "hint": resolved_hint,
                    }
                )
            )
        else:
            print(f"ERROR_CODE: {error_code}", file=sys.stderr)
            print(message, file=sys.stderr)
            if resolved_hint:
                print(f"Hint: {resolved_hint}", file=sys.stderr)
    sys.exit(exit_code)


def print_human(*args, **kwargs):
    """Print any human-readable text (progress, warnings, tables, diagnostics).

    Drop-in replacement for print() in CLI command handlers.
    Keeps stdout clean for the JSON envelope in agent mode.
    Usage: print_human("Starting shutdown of NVFLARE")
    """
    kwargs.setdefault("file", _human_stream())
    print(*args, **kwargs)


def prompt_yn(question: str, default_no: bool = True) -> bool:
    """Write a Y/N prompt to stderr (agent mode) or stdout (human mode) and read the answer from stdin.

    Returns True if the user answered Y/y, False otherwise.
    Writes the prompt to stderr in agent mode so that stdout contains only JSON.
    Callers must check sys.stdin.isatty() and handle --force before calling.

    Usage:
        if not cmd_args.force:
            if not sys.stdin.isatty():
                output_error("INVALID_ARGS", exit_code=4, detail="use --force in non-interactive mode")
                return
            if not prompt_yn(f"Delete job '{job_id}'?"):
                print_human("Cancelled.")
                return
    """
    suffix = " [y/N] " if default_no else " [Y/n] "
    stream = _human_stream()
    stream.write(question + suffix)
    stream.flush()
    answer = sys.stdin.readline().strip().upper()
    return answer == "Y"
