schema_version: 1
cc_deployment_mode: coco
cpu_tee: amd_sev_snp
gpu_tee: nvidia_cc
attestation:
  service: trustee
workload:
  source:
    type: docker_build
    context: ./site-1
    dockerfile: Dockerfile
coco:
  release_name: site-1-v1
  registry: coco_workloads
  registry_repository: workloads/site-1
  platform_config_file: ../admin/platform.env
