api_version: 3
name: coco_project
description: NVFlare with client-only AMD SEV-SNP and NVIDIA CoCo protection

participants:
  - name: server.example.com
    type: server
    org: example
    fed_learn_port: 8002
  - name: site-1
    type: client
    org: example
    cc_config: cc_site-1.yml
  - name: admin@example.com
    type: admin
    org: example
    role: project_admin

builders:
  - path: nvflare.lighter.impl.workspace.WorkspaceBuilder
  - path: nvflare.lighter.impl.static_file.StaticFileBuilder
    args:
      config_folder: config
  - path: nvflare.lighter.impl.cert.CertBuilder
  - path: nvflare.lighter.cc_provision.impl.cc.CCBuilder
  - path: nvflare.lighter.impl.signature.SignatureBuilder

packager:
  path: nvflare.lighter.cc_provision.impl.coco_packager.CoCoPackager
  args:
    build_image_cmd: ../admin/build_coco_image.sh
