openapi: 3.0.0
info:
  title: Flare Edge Gateway API (FEG)
  version: 1.0.1

servers:
  - url: http://flare.nvidia.com/edge/v1
    description: Edge device training API for NVFlare

paths:
  /job:
    post:
      summary: Request to participate in a job
      parameters:
        - $ref: "#/components/parameters/X-Flare-Device-ID"
        - $ref: "#/components/parameters/X-Flare-Device-Info"
        - $ref: "#/components/parameters/X-Flare-User-Info"

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JobRequest"

      responses:
        "200":
          description: Response for job request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JobResponse"

        "400":
          description: Request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "403":
          description: Authentication/permission error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /task:
    get:
      summary: Get a task
      parameters:
        - $ref: "#/components/parameters/X-Flare-Device-ID"
        - $ref: "#/components/parameters/X-Flare-Device-Info"
        - $ref: "#/components/parameters/X-Flare-User-Info"
        - name: job_id
          in: query
          required: false
          schema:
            type: string

      responses:
        "200":
          description: Response for task request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "400":
          description: Request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "403":
          description: Authentication/permission error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /result:
    post:
      summary: Report result for the task
      parameters:
        - $ref: "#/components/parameters/X-Flare-Device-ID"
        - $ref: "#/components/parameters/X-Flare-Device-Info"
        - $ref: "#/components/parameters/X-Flare-User-Info"
        - name: job_id
          in: query
          required: true
          schema:
            type: string
        - name: task_id
          in: query
          description: The task ID
          required: true
          schema:
            type: string
        - name: task_name
          in: query
          description: The task name
          required: false
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResultReport"

      responses:
        "200":
          description: Response for task result reporting
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultResponse"

        "400":
          description: Request error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "403":
          description: Authentication/permission error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:

  headers:

    X-Flare-Device-ID:
      description: The device ID
      schema:
        type: string

  parameters:

    X-Flare-Device-ID:
      name: X-Flare-Device-ID
      in: header
      description: The device ID
      required: true
      schema:
        type: string

    X-Flare-Device-Info:
      name: X-Flare-Device-Info
      in: header
      description: Extra device info encoded as query string
      required: false
      schema:
        type: string

    X-Flare-User-Info:
      name: X-Flare-User-Info
      in: header
      description: User and auth info encoded as query string
      required: false
      schema:
        type: string


  schemas:

    JobRequest:
      description: A request to join studies
      type: object
      properties:
        capabilities:
          type: object

    JobResponse:
      description: Response to job request
      type: object
      properties:
        status:
          type: string
          enum: [OK, RETRY, DONE]
        job_id:
          type: string
        job_name:
          type: string
        method:
          type: string
        job_data:
          type: object
        retry_wait:
          type: integer
          format: int64

    TaskResponse:
      description: Response to task request
      type: object
      properties:
        status:
          type: string
          enum: [OK, DONE, RETRY]
        task_name:
          type: string
        task_id:
          type: string
        task_data:
          type: object

    ResultReport:
      description: Report result back for the task
      type: object
      properties:
        result:
          type: object

    ResultResponse:
      description: Response to result reporting
      type: object
      properties:
        status:
          type: string
          enum: [OK, DONE, INVALID]
        task_id:
          type: string
        task_name:
          type: string
        message:
          type: string
        retry_wait:
          type: integer
          format: int64

    ErrorResponse:
      description: Error response to a request
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        details:
          type: object

    UserInfo:
      description: User and auth information in the header, encoded as query-string
      type: object
      properties:
        user_id:
          type: string
        user_name:
          type: string
        access_token:
          type: string
        auth_token:
          type: string
        auth_session:
          type: string

    DeviceInfo:
      description: Edge device information in the header, encoded as query-string
      type: object
      properties:
        device_id:
          type: string
        app_name:
          type: string
        app_version:
          type: string
        platform:
          type: string
        platform_version:
          type: string
