apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: nvflare-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: statsd
        static_configs:
          - targets: ["statsd-exporter:9102"]
