name: azure-server

clouds:
  azure:
    kubeconfig: ../../.tmp/kubeconfigs/azure.yaml
    image: "<acr>.azurecr.io/<repo>:<tag>"
    resource_group: myResourceGroup
    location: westus2
    helm_overrides: []
    pvc_config:
      nvflws:   { sc: managed-csi,   access: ReadWriteOnce, size: 10Gi }
      nvfldata: { sc: managed-csi,   access: ReadWriteOnce, size: 1Gi  }

participants:
  - { name: azure-server,   cloud: azure, namespace: nvflare-server,   role: server }
  - { name: azure-client-1, cloud: azure, namespace: nvflare-client-1, role: client }
