defaults:
  - base_infer_config
  # allow this config to override defaults
  - _self_

name: ESM1nv_Inference
desc: Minimum configuration for initializing a ESM1nv model for inference.

model:
  post_process: False
  tokenizer:
    vocab_path: models/vocab/protein_sequence.vocab
    model_path: models/vocab/protein_sequence_sentencepiece.model
  downstream_task:
    restore_from_path: "models/esm1nv.nemo"
    outputs: [embeddings, hiddens] # Which outputs to extract per sample (a value or list). Possible values: hiddens, embeddings.
  data:
    dataset_path: /tmp/fasta/mixed_soft # full path to dataset (can include range or a list)
    output_fname: "" # output file, inferred based on dataset_path if empty

target: bionemo.model.protein.esm1nv.esm1nv_model.ESM1nvModel  # path to model class to load
infer_target: bionemo.model.protein.esm1nv.infer.ESM1nvInference # path to inference class to load