# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nvflare.app_opt.flower.proto.fleet_pb2 as fleet__pb2


class NvFlowerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReceive = channel.unary_unary(
                '/nvflower.NvFlower/SendReceive',
                request_serializer=fleet__pb2.MessageContainer.SerializeToString,
                response_deserializer=fleet__pb2.MessageContainer.FromString,
                )


class NvFlowerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendReceive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NvFlowerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReceive': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReceive,
                    request_deserializer=fleet__pb2.MessageContainer.FromString,
                    response_serializer=fleet__pb2.MessageContainer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nvflower.NvFlower', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NvFlower(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendReceive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nvflower.NvFlower/SendReceive',
            fleet__pb2.MessageContainer.SerializeToString,
            fleet__pb2.MessageContainer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
