version: '3.8'

services:
  keycloak:
   # image: quay.io/keycloak/keycloak:24.0.1
    image: bitnami/keycloak:24
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/keycloak-setup
    depends_on:
      - db
    entrypoint: ["/bin/sh", "-c", "/opt/keycloak-setup/init.sh && /opt/keycloak/bin/kc.sh start-dev"]
    
  db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
