#!/bin/sh
# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu
builder_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
export PYTHONPATH="$builder_dir${PYTHONPATH:+:$PYTHONPATH}"
if [ -n "${CVM_BUILDER_PYTHON:-}" ]; then
    python=$CVM_BUILDER_PYTHON
elif [ -x "$builder_dir/.venv/bin/python" ]; then
    python=$builder_dir/.venv/bin/python
else
    python=python3
fi
exec "$python" -m cvm.trustee.inspect_tcb "$@"
