name: post-merge

on:
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch:

concurrency:
  group: post-merge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cron-trigger:
    if: github.repository == 'NVIDIA/NVFlare' # avoid triggering in forked repo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron triggered post-merge run..."

  unit-tests:
    needs: cron-trigger
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: PYTHONPATH=$(pwd) ./runtest.sh

  example-tests:
    needs: cron-trigger
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: |
          export PYTHONPATH=$(pwd)
          cd test/app_testing
          ./run_example_tests.sh

  app-tests:
    needs: cron-trigger
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: |
          export PYTHONPATH=$(pwd)
          cd test/app_testing
          ./run_app_tests.sh

  wheel-build:
    needs: cron-trigger
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: pip install build twine torch torchvision
      - run: python3 -m build --wheel
